# Generated by Django 4.2.15 on 2024-09-19 16:41

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Tickets',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid1, primary_key=True, serialize=False)),
                ('url', models.CharField(db_index=True, max_length=100)),
                ('user', models.IntegerField(default=0)),
                ('message', models.CharField(default='', max_length=200)),
                ('status', models.IntegerField(default=0)),
                ('create_time', models.IntegerField(default=0)),
                ('start_time', models.IntegerField(default=0)),
                ('end_time', models.IntegerField(default=0)),
                ('code', models.TextField(default='', max_length=30000)),
            ],
            options={
                'db_table': 'tickets',
            },
        ),
        migrations.CreateModel(
            name='UserLeave',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user', models.IntegerField(default=0)),
                ('status', models.IntegerField(default=0)),
                ('reason', models.CharField(max_length=200)),
                ('create_time', models.IntegerField(default=0)),
                ('start_time', models.IntegerField(default=0)),
                ('end_time', models.IntegerField(default=0)),
            ],
            options={
                'db_table': 'user_leave',
            },
        ),
        migrations.CreateModel(
            name='Users',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=20)),
                ('password', models.CharField(max_length=40)),
                ('nickname', models.CharField(max_length=20)),
                ('banned', models.BooleanField(default=False)),
                ('status', models.IntegerField(default=1)),
                ('telephone', models.CharField(max_length=20)),
                ('role', models.IntegerField(default=0)),
                ('last_time', models.IntegerField(default=0)),
            ],
            options={
                'db_table': 'users',
            },
        ),
        migrations.CreateModel(
            name='UserTicket',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user', models.IntegerField(default=0)),
                ('total', models.IntegerField(default=0)),
                ('years', models.CharField(max_length=20)),
            ],
            options={
                'db_table': 'user_ticket',
            },
        ),
    ]
