# Generated by Django 4.2.15 on 2024-09-19 05:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('workload', '0002_alter_tickets_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='users',
            name='last_time',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='tickets',
            name='id',
            field=models.UUIDField(primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='tickets',
            name='url',
            field=models.CharField(db_index=True, max_length=100),
        ),
    ]
