# Generated by Django 4.2.15 on 2024-09-19 05:52

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('workload', '0003_users_last_time_alter_tickets_id_alter_tickets_url'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tickets',
            name='id',
            field=models.UUIDField(default=uuid.uuid1, primary_key=True, serialize=False),
        ),
    ]
